const UserStatus = Object.freeze({
  NOT_STARATED: 0,
  COMPLETED: 1,
  IN_PROGRESS: 2,
  APPLICATION_VALIDATED: 3,
  APPLICATION_REJECTED: 4,
  AWARD_SHORTLISTED: 5,
  AWARD_VALIDATED: 6,
  AWARDED_PENDING_ACCEPTANCE: 7,
  AWARD_ACCEPTED: 8,
  AWARD_REJECTED: 9,
});
export default UserStatus;
